name: test-action
on:
  push:
    branches: [master, main]

env:
  PROJECT_DIRECTORY: "./engine/middleware"

jobs:
  testing1:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.share-status.outputs.status}}
    strategy:
      matrix:
        node-version: ['10']
    steps:
      - uses: actions/checkout@v2
        with: 
          path: "kms-secrets-manager-action"
      - name: Using Node.js
        run: |
          apt update && apt install nodejs -y && apt install npm -y
      - run: ls -la
      - name: Installing Secrets modules
        run: npm install --production
      - name: Getting secrets 
        uses: ./
        with: 
          AWS_EKS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_EKS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          eks_secrets_configs: '[{ "secret_name": "test/kuntur/bot", "output_secret_name": "compliance-nseuqe" }, { "secret_name": "test/kuntur/bot", "output_secret_name": "compliance-nseuqe" }]'
          output_secret_namespace: 'compliance'
          output_type: 'yaml'
      - run: cat output.yaml