name: test-action
on:
  push:
    branches: [master, main]

env:
  PROJECT_DIRECTORY: "./engine/middleware"

jobs:
  green-checks:
    runs-on: ubuntu-latest
    outputs:
      status: ${{steps.share-status.outputs.status}}
    strategy:
      matrix:
        node-version: ['10']
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        run: |
          apt update && apt install nodejs -y && apt install npm -y
      - name: Getting secrets 
        uses: ./
      - name: Update npm
        run: npm install -g npm@next # We need to update npm to a version grater than 7 in order to make the matchbox work
